apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-order-config
  labels:
    app: order
    tier: backend
data:
  APP_ENV: "production"
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "40043"
  DB_HOST: "lms-postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "lms_order_db"
  DB_SSL_MODE: "disable"
  DB_MAX_OPEN_CONNS: "25"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "5m"
  USER_SERVICE_ADDR: "lms-user-service:40041"
  BOOK_SERVICE_ADDR: "lms-book-service:40042"
  RABBITMQ_URL: "amqp://guest:guest@lms-rabbitmq:5672/"
  RABBITMQ_EXCHANGE: "order-events"
  BROKER_TYPE: "rabbitmq"
