apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-book-service
  labels:
    app: book
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
        tier: backend
    spec:
      containers:
        - name: book-service
          image: lms/book-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 40042
              protocol: TCP
          envFrom:
            - configMapRef:
                name: lms-book-config
            - secretRef:
                name: lms-book-secret
          readinessProbe:
            tcpSocket:
              port: 40042
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 40042
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
