apiVersion: v1
kind: Service
metadata:
  name: lms-redis
  labels:
    app: redis
    tier: cache
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: 63379
      targetPort: 6379
