apiVersion: v1
kind: Secret
metadata:
  name: lms-user-secret
stringData:
  DB_PASSWORD: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: lms-book-secret
stringData:
  DB_PASSWORD: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: lms-order-secret
stringData:
  DB_PASSWORD: "CHANGE_ME"
