# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from order import order_pb2 as order_dot_order__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order/order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateOrder = channel.unary_unary(
                '/order.v1.OrderService/CreateOrder',
                request_serializer=order_dot_order__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/order.v1.OrderService/GetOrder',
                request_serializer=order_dot_order__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.ListMyOrders = channel.unary_unary(
                '/order.v1.OrderService/ListMyOrders',
                request_serializer=order_dot_order__pb2.ListMyOrdersRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/order.v1.OrderService/CancelOrder',
                request_serializer=order_dot_order__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.ListAllOrders = channel.unary_unary(
                '/order.v1.OrderService/ListAllOrders',
                request_serializer=order_dot_order__pb2.ListAllOrdersRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.ListOrdersResponse.FromString,
                _registered_method=True)
        self.UpdateOrderStatus = channel.unary_unary(
                '/order.v1.OrderService/UpdateOrderStatus',
                request_serializer=order_dot_order__pb2.UpdateOrderStatusRequest.SerializeToString,
                response_deserializer=order_dot_order__pb2.OrderResponse.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAllOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=order_dot_order__pb2.CreateOrderRequest.FromString,
                    response_serializer=order_dot_order__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=order_dot_order__pb2.GetOrderRequest.FromString,
                    response_serializer=order_dot_order__pb2.OrderResponse.SerializeToString,
            ),
            'ListMyOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyOrders,
                    request_deserializer=order_dot_order__pb2.ListMyOrdersRequest.FromString,
                    response_serializer=order_dot_order__pb2.ListOrdersResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=order_dot_order__pb2.CancelOrderRequest.FromString,
                    response_serializer=order_dot_order__pb2.OrderResponse.SerializeToString,
            ),
            'ListAllOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAllOrders,
                    request_deserializer=order_dot_order__pb2.ListAllOrdersRequest.FromString,
                    response_serializer=order_dot_order__pb2.ListOrdersResponse.SerializeToString,
            ),
            'UpdateOrderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrderStatus,
                    request_deserializer=order_dot_order__pb2.UpdateOrderStatusRequest.FromString,
                    response_serializer=order_dot_order__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.v1.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order.v1.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/CreateOrder',
            order_dot_order__pb2.CreateOrderRequest.SerializeToString,
            order_dot_order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/GetOrder',
            order_dot_order__pb2.GetOrderRequest.SerializeToString,
            order_dot_order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/ListMyOrders',
            order_dot_order__pb2.ListMyOrdersRequest.SerializeToString,
            order_dot_order__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/CancelOrder',
            order_dot_order__pb2.CancelOrderRequest.SerializeToString,
            order_dot_order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAllOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/ListAllOrders',
            order_dot_order__pb2.ListAllOrdersRequest.SerializeToString,
            order_dot_order__pb2.ListOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order.v1.OrderService/UpdateOrderStatus',
            order_dot_order__pb2.UpdateOrderStatusRequest.SerializeToString,
            order_dot_order__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
