apiVersion: v1
kind: Service
metadata:
  name: lms-postgres
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 15432
      targetPort: 5432
