// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: book/book.proto

package bookv1

import (
	v1 "github.com/DgHnG36/lib-management-system/shared/go/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author            string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn              string                 `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Category          string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	TotalQuantity     int32                  `protobuf:"varint,7,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,8,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Book) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Book) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

func (x *Book) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *Book) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Book) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type GetBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetBookRequest_Id
	//	*GetBookRequest_Title
	Identifier    isGetBookRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookRequest) GetIdentifier() isGetBookRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetBookRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetBookRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetBookRequest) GetTitle() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetBookRequest_Title); ok {
			return x.Title
		}
	}
	return ""
}

type isGetBookRequest_Identifier interface {
	isGetBookRequest_Identifier()
}

type GetBookRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetBookRequest_Title struct {
	Title string `protobuf:"bytes,2,opt,name=title,proto3,oneof"`
}

func (*GetBookRequest_Id) isGetBookRequest_Identifier() {}

func (*GetBookRequest_Title) isGetBookRequest_Identifier() {}

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *ListBooksRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBooksRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListBooksRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *ListBooksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateBookPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TotalQuantity int32                  `protobuf:"varint,6,opt,name=total_quantity,json=totalQuantity,proto3" json:"total_quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookPayload) Reset() {
	*x = CreateBookPayload{}
	mi := &file_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookPayload) ProtoMessage() {}

func (x *CreateBookPayload) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookPayload.ProtoReflect.Descriptor instead.
func (*CreateBookPayload) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBookPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookPayload) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBookPayload) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *CreateBookPayload) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBookPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBookPayload) GetTotalQuantity() int32 {
	if x != nil {
		return x.TotalQuantity
	}
	return 0
}

type CreateBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*CreateBookPayload   `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBooksRequest) Reset() {
	*x = CreateBooksRequest{}
	mi := &file_book_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBooksRequest) ProtoMessage() {}

func (x *CreateBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBooksRequest.ProtoReflect.Descriptor instead.
func (*CreateBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBooksRequest) GetBooks() []*CreateBookPayload {
	if x != nil {
		return x.Books
	}
	return nil
}

type CreateBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBooksResponse) Reset() {
	*x = CreateBooksResponse{}
	mi := &file_book_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBooksResponse) ProtoMessage() {}

func (x *CreateBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBooksResponse.ProtoReflect.Descriptor instead.
func (*CreateBooksResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *CreateBooksResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_book_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdateBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *UpdateBookRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateBookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeleteBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBooksRequest) Reset() {
	*x = DeleteBooksRequest{}
	mi := &file_book_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBooksRequest) ProtoMessage() {}

func (x *DeleteBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBooksRequest.ProtoReflect.Descriptor instead.
func (*DeleteBooksRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBooksRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_book_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{10}
}

func (x *CheckAvailabilityRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type CheckAvailabilityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable       bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_book_book_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{11}
}

func (x *CheckAvailabilityResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckAvailabilityResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

type UpdateBookQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChangeAmount  int32                  `protobuf:"varint,2,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookQuantityRequest) Reset() {
	*x = UpdateBookQuantityRequest{}
	mi := &file_book_book_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookQuantityRequest) ProtoMessage() {}

func (x *UpdateBookQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookQuantityRequest) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateBookQuantityRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UpdateBookQuantityRequest) GetChangeAmount() int32 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

type UpdateBookQuantityResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewAvailableQuantity int32                  `protobuf:"varint,3,opt,name=new_available_quantity,json=newAvailableQuantity,proto3" json:"new_available_quantity,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateBookQuantityResponse) Reset() {
	*x = UpdateBookQuantityResponse{}
	mi := &file_book_book_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookQuantityResponse) ProtoMessage() {}

func (x *UpdateBookQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_book_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookQuantityResponse) Descriptor() ([]byte, []int) {
	return file_book_book_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBookQuantityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBookQuantityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBookQuantityResponse) GetNewAvailableQuantity() int32 {
	if x != nil {
		return x.NewAvailableQuantity
	}
	return 0
}

var File_book_book_proto protoreflect.FileDescriptor

const file_book_book_proto_rawDesc = "" +
	"\n" +
	"\x0fbook/book.proto\x12\abook.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xe2\x02\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12%\n" +
	"\x0etotal_quantity\x18\a \x01(\x05R\rtotalQuantity\x12-\n" +
	"\x12available_quantity\x18\b \x01(\x05R\x11availableQuantity\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"1\n" +
	"\fBookResponse\x12!\n" +
	"\x04book\x18\x01 \x01(\v2\r.book.v1.BookR\x04book\"H\n" +
	"\x0eGetBookRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x16\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05titleB\f\n" +
	"\n" +
	"identifier\"\x8f\x01\n" +
	"\x10ListBooksRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12!\n" +
	"\fsearch_query\x18\x02 \x01(\tR\vsearchQuery\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"Y\n" +
	"\x11ListBooksResponse\x12#\n" +
	"\x05books\x18\x01 \x03(\v2\r.book.v1.BookR\x05books\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xba\x01\n" +
	"\x11CreateBookPayload\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x03 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12%\n" +
	"\x0etotal_quantity\x18\x06 \x01(\x05R\rtotalQuantity\"F\n" +
	"\x12CreateBooksRequest\x120\n" +
	"\x05books\x18\x01 \x03(\v2\x1a.book.v1.CreateBookPayloadR\x05books\"_\n" +
	"\x13CreateBooksResponse\x12#\n" +
	"\x05books\x18\x01 \x03(\v2\r.book.v1.BookR\x05books\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\"\xa3\x01\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"&\n" +
	"\x12DeleteBooksRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"3\n" +
	"\x18CheckAvailabilityRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"m\n" +
	"\x19CheckAvailabilityResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x05R\x11availableQuantity\"Y\n" +
	"\x19UpdateBookQuantityRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12#\n" +
	"\rchange_amount\x18\x02 \x01(\x05R\fchangeAmount\"\x86\x01\n" +
	"\x1aUpdateBookQuantityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x16new_available_quantity\x18\x03 \x01(\x05R\x14newAvailableQuantity2\x97\x04\n" +
	"\vBookService\x129\n" +
	"\aGetBook\x12\x17.book.v1.GetBookRequest\x1a\x15.book.v1.BookResponse\x12B\n" +
	"\tListBooks\x12\x19.book.v1.ListBooksRequest\x1a\x1a.book.v1.ListBooksResponse\x12H\n" +
	"\vCreateBooks\x12\x1b.book.v1.CreateBooksRequest\x1a\x1c.book.v1.CreateBooksResponse\x12?\n" +
	"\n" +
	"UpdateBook\x12\x1a.book.v1.UpdateBookRequest\x1a\x15.book.v1.BookResponse\x12C\n" +
	"\vDeleteBooks\x12\x1b.book.v1.DeleteBooksRequest\x1a\x17.common.v1.BaseResponse\x12Z\n" +
	"\x11CheckAvailability\x12!.book.v1.CheckAvailabilityRequest\x1a\".book.v1.CheckAvailabilityResponse\x12]\n" +
	"\x12UpdateBookQuantity\x12\".book.v1.UpdateBookQuantityRequest\x1a#.book.v1.UpdateBookQuantityResponseBCZAgithub.com/DgHnG36/lib-management-system/shared/go/v1/book;bookv1b\x06proto3"

var (
	file_book_book_proto_rawDescOnce sync.Once
	file_book_book_proto_rawDescData []byte
)

func file_book_book_proto_rawDescGZIP() []byte {
	file_book_book_proto_rawDescOnce.Do(func() {
		file_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)))
	})
	return file_book_book_proto_rawDescData
}

var file_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_book_book_proto_goTypes = []any{
	(*Book)(nil),                       // 0: book.v1.Book
	(*BookResponse)(nil),               // 1: book.v1.BookResponse
	(*GetBookRequest)(nil),             // 2: book.v1.GetBookRequest
	(*ListBooksRequest)(nil),           // 3: book.v1.ListBooksRequest
	(*ListBooksResponse)(nil),          // 4: book.v1.ListBooksResponse
	(*CreateBookPayload)(nil),          // 5: book.v1.CreateBookPayload
	(*CreateBooksRequest)(nil),         // 6: book.v1.CreateBooksRequest
	(*CreateBooksResponse)(nil),        // 7: book.v1.CreateBooksResponse
	(*UpdateBookRequest)(nil),          // 8: book.v1.UpdateBookRequest
	(*DeleteBooksRequest)(nil),         // 9: book.v1.DeleteBooksRequest
	(*CheckAvailabilityRequest)(nil),   // 10: book.v1.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),  // 11: book.v1.CheckAvailabilityResponse
	(*UpdateBookQuantityRequest)(nil),  // 12: book.v1.UpdateBookQuantityRequest
	(*UpdateBookQuantityResponse)(nil), // 13: book.v1.UpdateBookQuantityResponse
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*v1.PaginationRequest)(nil),       // 15: common.v1.PaginationRequest
	(*v1.BaseResponse)(nil),            // 16: common.v1.BaseResponse
}
var file_book_book_proto_depIdxs = []int32{
	14, // 0: book.v1.Book.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: book.v1.Book.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: book.v1.BookResponse.book:type_name -> book.v1.Book
	15, // 3: book.v1.ListBooksRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 4: book.v1.ListBooksResponse.books:type_name -> book.v1.Book
	5,  // 5: book.v1.CreateBooksRequest.books:type_name -> book.v1.CreateBookPayload
	0,  // 6: book.v1.CreateBooksResponse.books:type_name -> book.v1.Book
	2,  // 7: book.v1.BookService.GetBook:input_type -> book.v1.GetBookRequest
	3,  // 8: book.v1.BookService.ListBooks:input_type -> book.v1.ListBooksRequest
	6,  // 9: book.v1.BookService.CreateBooks:input_type -> book.v1.CreateBooksRequest
	8,  // 10: book.v1.BookService.UpdateBook:input_type -> book.v1.UpdateBookRequest
	9,  // 11: book.v1.BookService.DeleteBooks:input_type -> book.v1.DeleteBooksRequest
	10, // 12: book.v1.BookService.CheckAvailability:input_type -> book.v1.CheckAvailabilityRequest
	12, // 13: book.v1.BookService.UpdateBookQuantity:input_type -> book.v1.UpdateBookQuantityRequest
	1,  // 14: book.v1.BookService.GetBook:output_type -> book.v1.BookResponse
	4,  // 15: book.v1.BookService.ListBooks:output_type -> book.v1.ListBooksResponse
	7,  // 16: book.v1.BookService.CreateBooks:output_type -> book.v1.CreateBooksResponse
	1,  // 17: book.v1.BookService.UpdateBook:output_type -> book.v1.BookResponse
	16, // 18: book.v1.BookService.DeleteBooks:output_type -> common.v1.BaseResponse
	11, // 19: book.v1.BookService.CheckAvailability:output_type -> book.v1.CheckAvailabilityResponse
	13, // 20: book.v1.BookService.UpdateBookQuantity:output_type -> book.v1.UpdateBookQuantityResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_book_book_proto_init() }
func file_book_book_proto_init() {
	if File_book_book_proto != nil {
		return
	}
	file_book_book_proto_msgTypes[2].OneofWrappers = []any{
		(*GetBookRequest_Id)(nil),
		(*GetBookRequest_Title)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_book_proto_rawDesc), len(file_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_book_proto_goTypes,
		DependencyIndexes: file_book_book_proto_depIdxs,
		MessageInfos:      file_book_book_proto_msgTypes,
	}.Build()
	File_book_book_proto = out.File
	file_book_book_proto_goTypes = nil
	file_book_book_proto_depIdxs = nil
}
