# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from book import book_pb2 as book_dot_book__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book/book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/book.v1.BookService/GetBook',
                request_serializer=book_dot_book__pb2.GetBookRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.BookResponse.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/book.v1.BookService/ListBooks',
                request_serializer=book_dot_book__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.CreateBooks = channel.unary_unary(
                '/book.v1.BookService/CreateBooks',
                request_serializer=book_dot_book__pb2.CreateBooksRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.CreateBooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/book.v1.BookService/UpdateBook',
                request_serializer=book_dot_book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.BookResponse.FromString,
                _registered_method=True)
        self.DeleteBooks = channel.unary_unary(
                '/book.v1.BookService/DeleteBooks',
                request_serializer=book_dot_book__pb2.DeleteBooksRequest.SerializeToString,
                response_deserializer=common__pb2.BaseResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/book.v1.BookService/CheckAvailability',
                request_serializer=book_dot_book__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.UpdateBookQuantity = channel.unary_unary(
                '/book.v1.BookService/UpdateBookQuantity',
                request_serializer=book_dot_book__pb2.UpdateBookQuantityRequest.SerializeToString,
                response_deserializer=book_dot_book__pb2.UpdateBookQuantityResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBookQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=book_dot_book__pb2.GetBookRequest.FromString,
                    response_serializer=book_dot_book__pb2.BookResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=book_dot_book__pb2.ListBooksRequest.FromString,
                    response_serializer=book_dot_book__pb2.ListBooksResponse.SerializeToString,
            ),
            'CreateBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooks,
                    request_deserializer=book_dot_book__pb2.CreateBooksRequest.FromString,
                    response_serializer=book_dot_book__pb2.CreateBooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book_dot_book__pb2.UpdateBookRequest.FromString,
                    response_serializer=book_dot_book__pb2.BookResponse.SerializeToString,
            ),
            'DeleteBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBooks,
                    request_deserializer=book_dot_book__pb2.DeleteBooksRequest.FromString,
                    response_serializer=common__pb2.BaseResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=book_dot_book__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=book_dot_book__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'UpdateBookQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBookQuantity,
                    request_deserializer=book_dot_book__pb2.UpdateBookQuantityRequest.FromString,
                    response_serializer=book_dot_book__pb2.UpdateBookQuantityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book.v1.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('book.v1.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/GetBook',
            book_dot_book__pb2.GetBookRequest.SerializeToString,
            book_dot_book__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/ListBooks',
            book_dot_book__pb2.ListBooksRequest.SerializeToString,
            book_dot_book__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/CreateBooks',
            book_dot_book__pb2.CreateBooksRequest.SerializeToString,
            book_dot_book__pb2.CreateBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/UpdateBook',
            book_dot_book__pb2.UpdateBookRequest.SerializeToString,
            book_dot_book__pb2.BookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/DeleteBooks',
            book_dot_book__pb2.DeleteBooksRequest.SerializeToString,
            common__pb2.BaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/CheckAvailability',
            book_dot_book__pb2.CheckAvailabilityRequest.SerializeToString,
            book_dot_book__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBookQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book.v1.BookService/UpdateBookQuantity',
            book_dot_book__pb2.UpdateBookQuantityRequest.SerializeToString,
            book_dot_book__pb2.UpdateBookQuantityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
