// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: order/order.proto

package orderv1

import (
	v1 "github.com/DgHnG36/lib-management-system/shared/go/v1"
	book "github.com/DgHnG36/lib-management-system/shared/go/v1/book"
	user "github.com/DgHnG36/lib-management-system/shared/go/v1/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_PENDING            OrderStatus = 1
	OrderStatus_APPROVED           OrderStatus = 2
	OrderStatus_BORROWED           OrderStatus = 3
	OrderStatus_RETURNED           OrderStatus = 4
	OrderStatus_CANCELED           OrderStatus = 5
	OrderStatus_OVERDUE            OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "PENDING",
		2: "APPROVED",
		3: "BORROWED",
		4: "RETURNED",
		5: "CANCELED",
		6: "OVERDUE",
	}
	OrderStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"PENDING":            1,
		"APPROVED":           2,
		"BORROWED":           3,
		"RETURNED":           4,
		"CANCELED":           5,
		"OVERDUE":            6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Borrower      *user.User             `protobuf:"bytes,2,opt,name=borrower,proto3" json:"borrower,omitempty"`
	BorrowedBooks []*book.Book           `protobuf:"bytes,3,rep,name=borrowed_books,json=borrowedBooks,proto3" json:"borrowed_books,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	BorrowDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	ReturnDate    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	PenaltyAmount int32                  `protobuf:"varint,8,opt,name=penalty_amount,json=penaltyAmount,proto3" json:"penalty_amount,omitempty"`
	Note          string                 `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetBorrower() *user.User {
	if x != nil {
		return x.Borrower
	}
	return nil
}

func (x *Order) GetBorrowedBooks() []*book.Book {
	if x != nil {
		return x.BorrowedBooks
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_STATUS_UNSPECIFIED
}

func (x *Order) GetBorrowDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BorrowDate
	}
	return nil
}

func (x *Order) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Order) GetReturnDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ReturnDate
	}
	return nil
}

func (x *Order) GetPenaltyAmount() int32 {
	if x != nil {
		return x.PenaltyAmount
	}
	return 0
}

func (x *Order) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookIds       []string               `protobuf:"bytes,2,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	BorrowDays    int32                  `protobuf:"varint,3,opt,name=borrow_days,json=borrowDays,proto3" json:"borrow_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

func (x *CreateOrderRequest) GetBorrowDays() int32 {
	if x != nil {
		return x.BorrowDays
	}
	return 0
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListMyOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FilterStatus  OrderStatus            `protobuf:"varint,3,opt,name=filter_status,json=filterStatus,proto3,enum=order.v1.OrderStatus" json:"filter_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersRequest) Reset() {
	*x = ListMyOrdersRequest{}
	mi := &file_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersRequest) ProtoMessage() {}

func (x *ListMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyOrdersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListMyOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMyOrdersRequest) GetFilterStatus() OrderStatus {
	if x != nil {
		return x.FilterStatus
	}
	return OrderStatus_STATUS_UNSPECIFIED
}

type ListAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	FilterStatus  OrderStatus            `protobuf:"varint,2,opt,name=filter_status,json=filterStatus,proto3,enum=order.v1.OrderStatus" json:"filter_status,omitempty"`
	SearchUserId  string                 `protobuf:"bytes,3,opt,name=search_user_id,json=searchUserId,proto3" json:"search_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOrdersRequest) Reset() {
	*x = ListAllOrdersRequest{}
	mi := &file_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOrdersRequest) ProtoMessage() {}

func (x *ListAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListAllOrdersRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAllOrdersRequest) GetFilterStatus() OrderStatus {
	if x != nil {
		return x.FilterStatus
	}
	return OrderStatus_STATUS_UNSPECIFIED
}

func (x *ListAllOrdersRequest) GetSearchUserId() string {
	if x != nil {
		return x.SearchUserId
	}
	return ""
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CancelReason  string                 `protobuf:"bytes,3,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelOrderRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	NewStatus     OrderStatus            `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=order.v1.OrderStatus" json:"new_status,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_order_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_order_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_order_order_proto protoreflect.FileDescriptor

const file_order_order_proto_rawDesc = "" +
	"\n" +
	"\x11order/order.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\x1a\x0fuser/user.proto\x1a\x0fbook/book.proto\"\x89\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\bborrower\x18\x02 \x01(\v2\r.user.v1.UserR\bborrower\x124\n" +
	"\x0eborrowed_books\x18\x03 \x03(\v2\r.book.v1.BookR\rborrowedBooks\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12;\n" +
	"\vborrow_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"borrowDate\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12;\n" +
	"\vreturn_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"returnDate\x12%\n" +
	"\x0epenalty_amount\x18\b \x01(\x05R\rpenaltyAmount\x12\x12\n" +
	"\x04note\x18\t \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"6\n" +
	"\rOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"i\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bbook_ids\x18\x02 \x03(\tR\abookIds\x12\x1f\n" +
	"\vborrow_days\x18\x03 \x01(\x05R\n" +
	"borrowDays\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xa8\x01\n" +
	"\x13ListMyOrdersRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12:\n" +
	"\rfilter_status\x18\x03 \x01(\x0e2\x15.order.v1.OrderStatusR\ffilterStatus\"\xb6\x01\n" +
	"\x14ListAllOrdersRequest\x12<\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1c.common.v1.PaginationRequestR\n" +
	"pagination\x12:\n" +
	"\rfilter_status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\ffilterStatus\x12$\n" +
	"\x0esearch_user_id\x18\x03 \x01(\tR\fsearchUserId\"^\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"m\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rcancel_reason\x18\x03 \x01(\tR\fcancelReason\"\x7f\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x124\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\tnewStatus\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note*w\n" +
	"\vOrderStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bAPPROVED\x10\x02\x12\f\n" +
	"\bBORROWED\x10\x03\x12\f\n" +
	"\bRETURNED\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x05\x12\v\n" +
	"\aOVERDUE\x10\x062\xc8\x03\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x17.order.v1.OrderResponse\x12>\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x17.order.v1.OrderResponse\x12K\n" +
	"\fListMyOrders\x12\x1d.order.v1.ListMyOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12D\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x17.order.v1.OrderResponse\x12M\n" +
	"\rListAllOrders\x12\x1e.order.v1.ListAllOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12P\n" +
	"\x11UpdateOrderStatus\x12\".order.v1.UpdateOrderStatusRequest\x1a\x17.order.v1.OrderResponseBEZCgithub.com/DgHnG36/lib-management-system/shared/go/v1/order;orderv1b\x06proto3"

var (
	file_order_order_proto_rawDescOnce sync.Once
	file_order_order_proto_rawDescData []byte
)

func file_order_order_proto_rawDescGZIP() []byte {
	file_order_order_proto_rawDescOnce.Do(func() {
		file_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)))
	})
	return file_order_order_proto_rawDescData
}

var file_order_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_order_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: order.v1.OrderStatus
	(*Order)(nil),                    // 1: order.v1.Order
	(*OrderResponse)(nil),            // 2: order.v1.OrderResponse
	(*CreateOrderRequest)(nil),       // 3: order.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),          // 4: order.v1.GetOrderRequest
	(*ListMyOrdersRequest)(nil),      // 5: order.v1.ListMyOrdersRequest
	(*ListAllOrdersRequest)(nil),     // 6: order.v1.ListAllOrdersRequest
	(*ListOrdersResponse)(nil),       // 7: order.v1.ListOrdersResponse
	(*CancelOrderRequest)(nil),       // 8: order.v1.CancelOrderRequest
	(*UpdateOrderStatusRequest)(nil), // 9: order.v1.UpdateOrderStatusRequest
	(*user.User)(nil),                // 10: user.v1.User
	(*book.Book)(nil),                // 11: book.v1.Book
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*v1.PaginationRequest)(nil),     // 13: common.v1.PaginationRequest
}
var file_order_order_proto_depIdxs = []int32{
	10, // 0: order.v1.Order.borrower:type_name -> user.v1.User
	11, // 1: order.v1.Order.borrowed_books:type_name -> book.v1.Book
	0,  // 2: order.v1.Order.status:type_name -> order.v1.OrderStatus
	12, // 3: order.v1.Order.borrow_date:type_name -> google.protobuf.Timestamp
	12, // 4: order.v1.Order.due_date:type_name -> google.protobuf.Timestamp
	12, // 5: order.v1.Order.return_date:type_name -> google.protobuf.Timestamp
	12, // 6: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	12, // 7: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: order.v1.OrderResponse.order:type_name -> order.v1.Order
	13, // 9: order.v1.ListMyOrdersRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 10: order.v1.ListMyOrdersRequest.filter_status:type_name -> order.v1.OrderStatus
	13, // 11: order.v1.ListAllOrdersRequest.pagination:type_name -> common.v1.PaginationRequest
	0,  // 12: order.v1.ListAllOrdersRequest.filter_status:type_name -> order.v1.OrderStatus
	1,  // 13: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	0,  // 14: order.v1.UpdateOrderStatusRequest.new_status:type_name -> order.v1.OrderStatus
	3,  // 15: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	4,  // 16: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	5,  // 17: order.v1.OrderService.ListMyOrders:input_type -> order.v1.ListMyOrdersRequest
	8,  // 18: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	6,  // 19: order.v1.OrderService.ListAllOrders:input_type -> order.v1.ListAllOrdersRequest
	9,  // 20: order.v1.OrderService.UpdateOrderStatus:input_type -> order.v1.UpdateOrderStatusRequest
	2,  // 21: order.v1.OrderService.CreateOrder:output_type -> order.v1.OrderResponse
	2,  // 22: order.v1.OrderService.GetOrder:output_type -> order.v1.OrderResponse
	7,  // 23: order.v1.OrderService.ListMyOrders:output_type -> order.v1.ListOrdersResponse
	2,  // 24: order.v1.OrderService.CancelOrder:output_type -> order.v1.OrderResponse
	7,  // 25: order.v1.OrderService.ListAllOrders:output_type -> order.v1.ListOrdersResponse
	2,  // 26: order.v1.OrderService.UpdateOrderStatus:output_type -> order.v1.OrderResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_order_order_proto_init() }
func file_order_order_proto_init() {
	if File_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_order_proto_rawDesc), len(file_order_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_order_proto_goTypes,
		DependencyIndexes: file_order_order_proto_depIdxs,
		EnumInfos:         file_order_order_proto_enumTypes,
		MessageInfos:      file_order_order_proto_msgTypes,
	}.Build()
	File_order_order_proto = out.File
	file_order_order_proto_goTypes = nil
	file_order_order_proto_depIdxs = nil
}
