# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
from user import user_pb2 as user_dot_user__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/user.v1.UserService/Register',
                request_serializer=user_dot_user__pb2.RegisterRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/user.v1.UserService/Login',
                request_serializer=user_dot_user__pb2.LoginRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/user.v1.UserService/GetProfile',
                request_serializer=user_dot_user__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/user.v1.UserService/UpdateProfile',
                request_serializer=user_dot_user__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.UserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateVIPAccount = channel.unary_unary(
                '/user.v1.UserService/UpdateVIPAccount',
                request_serializer=user_dot_user__pb2.UpdateVIPAccountRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.UpdateVIPAccountResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/user.v1.UserService/ListUsers',
                request_serializer=user_dot_user__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.DeleteUsers = channel.unary_unary(
                '/user.v1.UserService/DeleteUsers',
                request_serializer=user_dot_user__pb2.DeleteUsersRequest.SerializeToString,
                response_deserializer=common__pb2.BaseResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVIPAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=user_dot_user__pb2.RegisterRequest.FromString,
                    response_serializer=user_dot_user__pb2.RegisterResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=user_dot_user__pb2.LoginRequest.FromString,
                    response_serializer=user_dot_user__pb2.LoginResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=user_dot_user__pb2.GetProfileRequest.FromString,
                    response_serializer=user_dot_user__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=user_dot_user__pb2.UpdateProfileRequest.FromString,
                    response_serializer=user_dot_user__pb2.UserProfileResponse.SerializeToString,
            ),
            'UpdateVIPAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVIPAccount,
                    request_deserializer=user_dot_user__pb2.UpdateVIPAccountRequest.FromString,
                    response_serializer=user_dot_user__pb2.UpdateVIPAccountResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=user_dot_user__pb2.ListUsersRequest.FromString,
                    response_serializer=user_dot_user__pb2.ListUsersResponse.SerializeToString,
            ),
            'DeleteUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUsers,
                    request_deserializer=user_dot_user__pb2.DeleteUsersRequest.FromString,
                    response_serializer=common__pb2.BaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Register',
            user_dot_user__pb2.RegisterRequest.SerializeToString,
            user_dot_user__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Login',
            user_dot_user__pb2.LoginRequest.SerializeToString,
            user_dot_user__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetProfile',
            user_dot_user__pb2.GetProfileRequest.SerializeToString,
            user_dot_user__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/UpdateProfile',
            user_dot_user__pb2.UpdateProfileRequest.SerializeToString,
            user_dot_user__pb2.UserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVIPAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/UpdateVIPAccount',
            user_dot_user__pb2.UpdateVIPAccountRequest.SerializeToString,
            user_dot_user__pb2.UpdateVIPAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/ListUsers',
            user_dot_user__pb2.ListUsersRequest.SerializeToString,
            user_dot_user__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/DeleteUsers',
            user_dot_user__pb2.DeleteUsersRequest.SerializeToString,
            common__pb2.BaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
