apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lms-dev

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: lms-gateway-secret
    envs:
      - ../../base/secrets/gateway.env
  - name: lms-user-secret
    envs:
      - ../../base/secrets/user.env
  - name: lms-book-secret
    envs:
      - ../../base/secrets/book.env
  - name: lms-order-secret
    envs:
      - ../../base/secrets/order.env
  - name: lms-notification-secret
    envs:
      - ../../base/secrets/notification.env
  - name: lms-redis-secret
    envs:
      - ../../base/secrets/redis.env
  - name: lms-postgres-secret
    envs:
      - ../../base/secrets/postgres.env
  - name: lms-rabbitmq-secret
    envs:
      - ../../base/secrets/rabbitmq.env

images:
  - name: lms/gateway-service
    newTag: dev
  - name: lms/user-service
    newTag: dev
  - name: lms/book-service
    newTag: dev
  - name: lms/order-service
    newTag: dev
  - name: lms/notification-service
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
    target:
      kind: Deployment

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: lms-gateway-service
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: lms-user-service
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: lms-book-service
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: lms-order-service
      spec:
        replicas: 1
